### ISSUE TITLE
Turn off the NVIDIA card with bbswitch when logging in and selected option is Intel

### ISSUE THREAD

**Issue by andrebrait** [tseliot/nvidia-prime#5]
Hi there.

I currently have forked and modified prime-indicator (which is unrelated to this package, of course) to meet the purpose of actually powering the NVIDIA GPU off using bbswitch when the user logs in and the selected option is intel (when $`prime-select query` returns `intel`) but I though that this functionality might be better suited to be included in nvidia-prime itself, since ubuntu-derived distros also use it and the ones that provide an app indicator to facilitate switching between dGPU and iGPU do not provide any means of actually turning the dGPU off.

This can potentially improve people's battery lives by as much as two times (mine went from 3:40 to 6:30, on average, on my Vostro 5470). Since this package provides a systemd service that turns the card back on when turning the computer off, the rare cases where the card would not turn on again when the computer is restarted while the dGPU is off should not be a problem.

Is there any reason why I sould not be thinking about doing this? (I can do this by forking, implementing the feature and then leaving a pull request after it's been well tested).

**Comment by tseliot** [comment]
Hi Andre,

If the dGPU is not being switched off (in Ubuntu 16.04), that is only because of missing support for recent nvidia drivers in gpu-manager. If you install ubuntu-drivers-common (from xenial-proposed), it should solve the problem. Here is the link to the SRU. Testing is welcome: https://bugs.launchpad.net/ubuntu/+source/ubuntu-drivers-common/+bug/1619306

**Comment by andrebrait** [comment]
I see then. I'll test it after I uninstall my indicator that does this manually. I wasn't even aware that gpu-manager existed. I'm using drivers from the Proprietary GPU Drivers ppa, (370.28) which is probably why I had this problem in the first place.

**Comment by andrebrait** [comment]
Is it possible/probable that Ubuntu would include, at some time, a GUI Indicator like mine to show which GPU is being used and the power status of the dGPU? I found this feature to be very useful when I tested Mint back when they added it.
