### ISSUE TITLE
turning off nvida card depends on nouveau

### ISSUE THREAD

**Issue by sudopluto** [tseliot/nvidia-prime#8]
this is not acceptable, loading nouveau in some skylake laptops, like mine, causes system instability.
please include bbswitch again

**Comment by tseliot** [comment]
I am already working on a system that doesn't require nouveau.

Alberto Milone

**Comment by sudopluto** [comment]
that's awesome to hear. sorry if I was a bit rude earlier, was just frustrated that there was a regression like this. https://github.com/timrichardson/Prime-Ubuntu-18.04 is working great for me as a sort of temp fix in the meantime
